# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Server.proto',
  package='serve',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cserver.proto\x12\x05serve\"\x1a\n\x0c\x46\x65tchRequest\x12\n\n\x02s1\x18\x01 \x01(\t\"0\n\x07reading\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x12\n\nmeterusage\x18\x02 \x01(\x02\x32:\n\x06Server\x12\x30\n\x05\x46\x65tch\x12\x13.serve.FetchRequest\x1a\x0e.serve.reading\"\x00\x30\x01\x62\x06proto3')
)




_FETCHREQUEST = _descriptor.Descriptor(
  name='FetchRequest',
  full_name='serve.FetchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s1', full_name='serve.FetchRequest.s1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=49,
)


_READING = _descriptor.Descriptor(
  name='reading',
  full_name='serve.reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='serve.reading.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meterusage', full_name='serve.reading.meterusage', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['FetchRequest'] = _FETCHREQUEST
DESCRIPTOR.message_types_by_name['reading'] = _READING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchRequest = _reflection.GeneratedProtocolMessageType('FetchRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:serve.FetchRequest)
  })
_sym_db.RegisterMessage(FetchRequest)

reading = _reflection.GeneratedProtocolMessageType('reading', (_message.Message,), {
  'DESCRIPTOR' : _READING,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:serve.reading)
  })
_sym_db.RegisterMessage(reading)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='serve.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=101,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fetch',
    full_name='serve.Server.Fetch',
    index=0,
    containing_service=None,
    input_type=_FETCHREQUEST,
    output_type=_READING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
