# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server_pb2 as server__pb2


class ServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Fetch = channel.unary_stream(
        '/serve.Server/Fetch',
        request_serializer=server__pb2.FetchRequest.SerializeToString,
        response_deserializer=server__pb2.reading.FromString,
        )


class ServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Fetch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Fetch': grpc.unary_stream_rpc_method_handler(
          servicer.Fetch,
          request_deserializer=server__pb2.FetchRequest.FromString,
          response_serializer=server__pb2.reading.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'serve.Server', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
